### ISSUE TITLE
No footstep sounds on steps (Try falkreath barracks)

### ISSUE THREAD

**Issue by cheesemanhugs** [Althro/Tinvaak#11] opened 2021-05-02 04:44 UTC
As described in title. 

Also, I've been playing this wonderful modlist A LOT lately. Its kinda consumed my life. That being the case I've noticed quite a few small problems here or there. Clipping furniture (usually a distinct interior conflict) and floating objects being the main things I've seen. I'm curious if I should be posting these small issues here or maybe the discord. because I'm sure you know about a lot of these small problems and I don't want to clutter up the issues tab.

**Comment by Althro** [comment] 2021-05-02 15:03
I'm in the process of making a consistency pass on the worldspace to ensure that everything looks ok and nothing's out of place. Foot-step stuff should be fixed in the next version as I've gone through and checked those. If you can note down areas where you see things, that will speed up my process as I will then be able to go to those locations and fix them.

**Comment by cheesemanhugs** [comment] 2021-05-03 02:06
Alr, I'll keep you posted

**Comment by Althro** [comment] 2021-05-14 09:11
Duplicate of #13

**Closed by Althro** 2021-05-14 09:11 UTC
